name: Sync to Gitee
on: push: branches: - main workflow_dispatch:
jobs: sync: runs-on: ubuntu-latest
steps:
  - name: Checkout GitHub Repo
    uses: actions/checkout@v3

  - name: Set Git Config
    run: |
      git config --global user.name "hungryM0"
      git config --global user.email "hungryM0@qq.com"

  - name: Push to Gitee
    env:
      GITEE_TOKEN: ${{ secrets.Gitee }}
    run: |
      git remote add gitee https://oauth2:${GITEE_TOKEN}@gitee.com/hungryM0/fuck-wjx.git
      git push -f gitee main